src/FN.Store/FN.Store.UI/Controllers/ContaController.cs
using FN.Store.Domain.Contracts.Repositories;
using FN.Store.Domain.Helpers;
using FN.Store.UI.ViewModels.Conta.Login;
using System.Web.Mvc;
using System.Web.Security;

namespace FN.Store.UI.Controllers
{
    public class ContaController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public ContaController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }


        [HttpGet]
        public ActionResult Login(string returnURL)
        {
            var model = new LoginVM() { ReturnURL = returnURL };
            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginVM model)
        {
            var usuario = _usuarioRepository.Get(model.Email);

            if (usuario == null)
                ModelState.AddModelError("Email", "O e-mail não localizado");
            else
            {
                if (usuario.Senha != model.Senha.Encrypt())
                    ModelState.AddModelError("Senha", "Senha inválida");
            }


            if (ModelState.IsValid)
            {
                FormsAuthentication.SetAuthCookie(model.Email, model.PermanecerLogado);

                if (!string.IsNullOrEmpty(model.ReturnURL) && Url.IsLocalUrl(model.ReturnURL))
                {
                    return Redirect(model.ReturnURL);
                }

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {}

    }
}

src/FN.Store/FN.Store.UI/Controllers/ProdutosController.cs
using FN.Store.Domain.Contracts.Repositories;
using System.Web.Mvc;
using FN.Store.UI.ViewModels.Produtos.Index.Maps;
using FN.Store.UI.ViewModels.Produtos.AddEdit.Maps;
using FN.Store.UI.ViewModels.Produtos.AddEdit;

namespace FN.Store.UI.Controllers
{

    [Authorize]
    public class ProdutosController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly ITipoDeProdutoRepository _tipoDeProdutoRepository;


        public ProdutosController(
            IProdutoRepository produtoRepository, 
            ITipoDeProdutoRepository tipoDeProdutoRepository)
        {
            _produtoRepository = produtoRepository;
            _tipoDeProdutoRepository = tipoDeProdutoRepository;
        }



        public ViewResult Index()
        {
            var produtos = _produtoRepository.Get().ToProdutoIndexVM();
            return View(produtos);
        }

        [HttpGet]
        public ViewResult AddEdit(int? id)
        {
            var produto = new ProdutoAddEditVM();

            if (id != null)
            {
                produto = _produtoRepository.Get((int)id).ToProdutoAddEditVM();
            }

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;
            return View(produto);
        }


        [HttpPost]
        public ActionResult AddEdit(ProdutoAddEditVM produtoVM)
        {
            var produto = produtoVM.ToProduto();

            if (ModelState.IsValid)
            {
                if (produto.Id == 0)
                {
                    _produtoRepository.Add(produto);
                }
                else
                {
                    _produtoRepository.Edit(produto);
                }

                return RedirectToAction("Index");
            }

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;

            return View(produto);
        }


        public ActionResult DelProd(int id)
        {

            var produto = _produtoRepository.Get(id);
            if (produto == null)
            {
                return HttpNotFound();
            }

            _produtoRepository.Delete(produto);
            return null;
        }


        protected override void Dispose(bool disposing)
        {}

    }
}

src/FN.Store/FN.Store.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/all.min.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <title>FN Store | @ViewBag.Title</title>
</head>
<body>

    @Html.Partial("_menu")

    <div class="container mt-3">
        @RenderBody()
    </div>

    <footer class="footer bg-info footer-custom">
        <div class="container">
            <span class="text-muted">&copy;@DateTime.Now.Year FN Corporation</span>
        </div>
    </footer>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    @RenderSection("scripts",false)

</body>
</html>

src/FN.Store/FN.Store.UI/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="#">FN Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">Página Inicial</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Produtos")">Produtos</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Sobre","Home")">Sobre</a>
            </li>

        </ul>

        <ul class="navbar-nav ml-auto">

            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @User.Identity.Name
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Trocar Senha</a>
                        <a class="dropdown-item" href="#">Meu Perfil</a>

                        <div class="dropdown-divider" href="#"></div>

                        <a class="dropdown-item" href="@Url.Action("LogOut", "Conta")">LogOut</a>
                    </div>
                </li>
            }
            else
            {
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Login","Conta")">Efetuar Login</a>
                </li>
            }
        </ul>


    </div>
</nav>